[package]
name = "swaptun_backend"
version = "0.1.0"
edition = "2024"

[workspace]
members = ["." , "api", "services","repositories"]
[features]
default=["full"]
full= ["swaptun-api/default"]

[dependencies]
swaptun-api = { path = "./api", default-features = false }
