[package]
name = "swaptun-repositories"
version = "0.1.0"
edition = "2024"

[dependencies]

chrono = { version = "0.4.40", features = ["serde"] }
sea-orm = { version = "1.1.7", features = [
  "sqlx-postgres",
  "runtime-tokio-native-tls",
  "macros",
] }
swaptun-models = { path = "../models" }